name: Build FetchIt Podman Desktop container
on: 
  push:
    branches: ["main", "release*"]
    tags: ["*"]
  pull_request:
    branches: ["main", "release*"]

env: 
  CONTAINER_IMAGE: "quay.io/fetchit/fetchit-desktop:latest"

jobs:
  image-build:
    name: Build FetchIt Podman Desktop container
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug

      - name: Login to the registry
        run: |
          [[ "${CONTROLLER_IMAGE}" =~ ^([^/]+)/[^/]+/[^/]+ ]] && REGISTRY="${BASH_REMATCH[1]}" || REGISTRY="quay.io"
          echo "Attempting docker login to: ${REGISTRY}"
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin ${REGISTRY}
    
      - name: "Build Operator Image"
        uses: docker/build-push-action@v2
        if: >
          (github.event_name == 'push' || github.event_name == 'schedule') &&
          (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))
        with:
          context: .
          file: "./Dockerfile"
          platforms: "linux/amd64,linux/arm64"
          push: true
          tags: ${{ env.CONTAINER_IMAGE }}

      - name: "Build Operator Image"
        uses: docker/build-push-action@v2
        if: >
          (github.event_name == 'push' || github.event_name == 'schedule') &&
          (github.ref != 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))
        with:
          context: .
          file: "./Dockerfile"
          platforms: "linux/amd64,linux/arm64"
          push: false
          tags: ${{ env.CONTAINER_IMAGE }}